language: go

go_import_path: github.com/src-d/gitbase

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

before_install:
  - docker pull pilosa/pilosa:v0.9.0
  - docker run -d --name pilosa -p 127.0.0.1:10101:10101 pilosa/pilosa:v0.9.0
  - docker ps -a
  - sudo apt-get install -y libonig2 libonig-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

before_script:
  - docker run -d --name bblfshd --privileged -p 9432:9432 -v /var/lib/bblfshd:/var/lib/bblfshd bblfsh/bblfshd
  - docker exec -it bblfshd bblfshctl driver install python bblfsh/python-driver
  - docker exec -it bblfshd bblfshctl driver install php bblfsh/php-driver

script:
  - make test-coverage codecov

jobs:
  include:
    - go: 1.10.x
      os: linux
      sudo: required
      dist: trusty
      services: [docker]

      before_deploy:
        - make packages

      after_deploy:
        - DOCKER_PUSH_LATEST=1 make docker-push

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*linux_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true

    - {go: tip, os: linux, sudo: required, dist: trusty, services: [docker]}

    - go: 1.10.x
      os: osx
      osx_image: xcode9.3

      before_install:
        - echo "skipping before_install for macOS"

      before_script:
        - echo "skipping before_script for macOS"

      script:
        - brew update
        - brew install oniguruma
        - make packages || echo "" # will fail because of docker being missing
        - if [ ! -f "build/gitbase_darwin_amd64/gitbase" ]; then echo "gitbase binary not generated" && exit 1; fi
        - cd build
        - tar -cvzf "gitbase_${TRAVIS_TAG}_darwin_amd64.tar.gz" gitbase_darwin_amd64
        - cd ..

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*darwin_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true
