language: go

go_import_path: github.com/src-d/gitbase

env:
  - GO111MODULE=on

matrix:
  fast_finish: true

before_script:
  - docker run -d --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd:v2.14.0-drivers
  - docker exec -it bblfshd bblfshctl driver list

script:
  - make test-coverage codecov
  - make ci-e2e

jobs:
  include:
    - go: 1.11.x
      os: linux
      sudo: required
      dist: trusty
      services: [docker]

      before_deploy:
        - make docker-push-latest-release
        - make static-package

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*linux_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true

    - go: 1.11.x
      os: osx
      osx_image: xcode9.3

      before_install:
        - echo "skipping before_install for macOS"

      before_script:
        - echo "skipping before_script for macOS"

      script:
        - make packages || echo "" # will fail because of docker being missing
        - if [ ! -f "build/gitbase_darwin_amd64/gitbase" ]; then echo "gitbase binary not generated" && exit 1; fi
        - cd build
        - tar -cvzf "gitbase_${TRAVIS_TAG}_darwin_amd64.tar.gz" gitbase_darwin_amd64
        - cd ..

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*darwin_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true
